YugiOh_NonDBVersion/Models/YugiOhCardViewModel.cs
using CardCore;

namespace YugiOh_NonDBVersion.Models;

public class YugiOhCardViewModel
{
    public string name { get; set; }
    public string descrtion { get; }
    public double[] prices { get; }
    public List<string> sets { get; }
    public List<string> smallCardImages { get; }
    public List<string> smallCardImageUrl { get; }
    public double highestPrice { get; set; }

    public YugiOhCardViewModel(YugiOhCardModel card)
    {
        name = card.cardName;
        descrtion = card.GetCardDescription();
        ICardPrice priceModel = card.GetCardPrice();
        if (priceModel != null)
            prices = new[]
            {
                priceModel.GetAmazonPrice(), priceModel.GetMarketPrice(), priceModel.GetCoolStuffPrice(),
                priceModel.GetCoolStuffPrice(), priceModel.GetEBayPrice(), priceModel.GetTcgPlayerPrice()
            };
        else
            prices = new[] { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };

        foreach (var VARIABLE in prices)
        {
            if (highestPrice < VARIABLE)
                highestPrice = VARIABLE;
        }
        
        smallCardImages = new List<string>();
        sets = new List<string>();
        smallCardImageUrl = new List<string>();
        List<ICardImage> images = card.GetAllImages();
        
            if (card.GetAllImages()[0].GetSmallImages() != null)
            {
                smallCardImages.Add(String.Format("data:image/png;base64,{0}",
                    Convert.ToBase64String(card.GetAllImages()[0].GetSmallImages())));
            }
            smallCardImageUrl.Add(card.GetAllImages()[0].GetSmallImageUrl());
        
        List<ICardSet> cardSets = card.GetAllCardSets();
        if (cardSets.Count <= 0)
        {
            ICardSet temp = new YugiOhSetModel();
            temp.SetSetName("No Set");
            cardSets.Add(temp);
        }
        foreach (ICardSet set in cardSets)
        {
            sets.Add(set.GetSetName());
        }
    }
}

YugiOh_NonDBVersion/Controllers/YugiOhCardController.cs
using System.Runtime.InteropServices;
using CardCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using YugiOh_NonDBVersion.Constants;
using YugiOh_NonDBVersion.Models;


namespace YugiOh_NonDBVersion.Controllers;

public class YugiOhCardController: Controller
{
    
    private readonly Settings settings;
    private YugiOhCreateCardModel createCardModel;

    public YugiOhCardController(IOptions<Settings> settings)
    {
        this.settings = settings.Value;
        createCardModel = new YugiOhCreateCardModel();
        string userName = Environment.UserName;
        this.settings.linuxFilePathLocation = this.settings.linuxFilePathLocation.Replace("[user]", userName);
        this.settings.windowsFilePathLocation = this.settings.windowsFilePathLocation.Replace("[user]", userName);
        
    }

    //Get
    public IActionResult Create()
    {
        return View(createCardModel);
    }

    [HttpPost]
    public IActionResult Create(string? cardName, string? cardSearchType)
    {
        if (string.IsNullOrEmpty(cardName) || string.IsNullOrEmpty(cardSearchType))
            return View(createCardModel);

        if (ModelState.IsValid)
        {
            if (DoesCardAlreadyExist(cardName) && cardSearchType.ToLower().Contains("name"))
            {
                TempData["success"] = "Card already exists please use the Detailed Refresh";
                return RedirectToAction("Index");
            }

            GetAndSaveCards(cardName, cardSearchType);
        }
        else
        {
            TempData["error"] = "Card was not saved";
            return View(createCardModel);
        }
        TempData["success"] = "Card was saved";
        return RedirectToAction("Index");
    }

    public IActionResult RefreshCard(string? cardName)
    {
        if (string.IsNullOrEmpty(cardName))
            return RedirectToAction("Index");

        if (ModelState.IsValid)
        {
            GetAndSaveCards(cardName,"Name Search");
        }

        return RedirectToAction("DetailedCard", new{cardName=cardName});
    }
    
    private void GetAndSaveCards(string cardName, string cardSearchType)
    {
        YugiOhConnection connection = new YugiOhConnection(cardName, YugiOhEnums.ConvertStringToSearchTerm(cardSearchType));

        JToken cardToken = connection.ConnectToWebsiteWithJson();

        JArray check = (JArray)cardToken["data"]!;
        foreach (JToken token in check)
        {
            YugiOhCardModel card = new YugiOhCardModel();
            card.CreateCardFromJson(token);
            if (!string.IsNullOrEmpty(card.cardName))
                SaveCardsToFile.SaveCard(card, GetLocationPath());
        }
    }


    public IActionResult DetailedCard(string? cardName)
    {
        if (string.IsNullOrEmpty(cardName))
        {
            return RedirectToAction("Index");
        }

        YugiOhDetailCardModel detailedView = new YugiOhDetailCardModel(
            (YugiOhCardModel)LoadingCardsFromFile.LoadCard(cardName, GetLocationPath(), TradingCardType.YugiOh));
        
        
        return View(detailedView);
    }
    
    public IActionResult Delete(String? cardName)
    {
        if (string.IsNullOrEmpty(cardName))
        {
            return RedirectToAction("Index");
        }

        RemoveCardInFile.DeleteCard(cardName, GetLocationPath());
        
        return RedirectToAction("Index");
    }

    public IActionResult Index()
    {
        List<YugiOhCardViewModel> listOfCards = ConvertToViewModel(LoadingCardsFromFile.LoadAllTheCards(GetLocationPath(),TradingCardType.YugiOh));

        return View(listOfCards);
    }

    private List<YugiOhCardViewModel> ConvertToViewModel(List<CardBase> cards)
    {
        List<YugiOhCardViewModel> tempCards = new List<YugiOhCardViewModel>();

        foreach (CardBase cardBase in cards)
        {
            if (cardBase is YugiOhCardModel yugiOhCardModel)
            {
                YugiOhCardViewModel tempCard = new YugiOhCardViewModel(yugiOhCardModel);
                tempCards.Add(tempCard);
            }
        }
        
        return tempCards;
    }

    private string GetLocationPath()
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            return settings.linuxFilePathLocation;
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            return settings.windowsFilePathLocation;
        }

        return settings.linuxFilePathLocation;
    }
    
    private bool DoesCardAlreadyExist(string cardName)
    {
        string finalpath = LoadingCardsFromFile.CheckFileIsThere(cardName, GetLocationPath());
        if (string.IsNullOrEmpty(finalpath))
        {
            return false;
        }

        return System.IO.File.Exists(finalpath);

    }
}

YugiOh_NonDBVersion/Views/YugiOhCard/Create.cshtml
@model YugiOhCreateCardModel


<form method = "post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Search For Card(s)</h2>
            <hr/>
        </div>
        @* This will allow for us to not have to use the span and instead just use this one line that will *@
        @* bring through all the errors for the form at the top neatly *@
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="cardName">Card Name To Search For</label>
            <input asp-for="cardName" class="form-control"/>
            @* <span asp-validation-for="Name" class="text-danger"></span> *@
        </div>
        <div class="btn-group mb-3" role="group" aria-label="Basic radio toggle button group" >
            @foreach (string radioBut in @Model.searchTermList)
            {
                <input asp-for="cardSearchType" class="btn-check" id="@radioBut" type="radio" name="cardSearchType" value="@radioBut" />
                <label asp-for="cardSearchType" type="radio" class="btn btn-outline-primary" for="@radioBut">@radioBut</label>      
            }
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Search</button>
        <a asp-controller="YugiOhCard" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

@section Scripts
{
    @{
        //This will bring through validtion checks we added on the server side to the client side, this way we do not hit the server 
        // everytime.
        <partial name="_ValidationScriptsPartial"/>        
    }
}

YugiOh_NonDBVersion/Views/YugiOhCard/Delete.cshtml
@model YugiOhCardViewModel

YugiOh_NonDBVersion/Views/YugiOhCard/DetailedCard.cshtml
@model YugiOhDetailCardModel

<form method = "post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">@Model.name</h2>
            <hr/>
        </div>
        <div class="col-8">
            <a asp-controller="YugiOhCard" asp-action="RefreshCard" asp-route-cardName="@Model.name" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>  Refresh Card
            </a>
        </div>
        <div asp-validation-summary="All"></div>
      <br/>
      <table class="table table-bordered table-striped" style="width:100%">
          <thead>
          <tr>
              <th>Description</th>
              <th>Image</th>
              <th>Sets</th>
              <th>Price</th>
          </tr>
          </thead>
           <tbody>
           <tr width="100%">
                      
                      <td style="width:30%">@Model.desc</td>
               <td>
                   @foreach (string img in Model.largeImages)
                   {
                       <img src="@img"/>    
                       <br/>
                       <br/>
                   }
                   
               </td>
               <td> @foreach (string obj in Model.setNames)
                    {
                        <p>@obj</p>
                        <br/>
                    }
               </td>
               @* List of items within the Sets Price. *@
               @* 0: Amazon, 1: tcgPlayer, 2: market, 3: eBay, 4: cool *@
               <td>
                   @foreach (double obj in Model.prices)
                   {
                       <p>R @Math.FusedMultiplyAdd(obj,20.0,0)</p>
                       <br/>
                   }
               </td>
           </tr>
           
              </tbody>
      </table>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="YugiOhCard" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

YugiOh_NonDBVersion/Views/YugiOhCard/Index.cshtml
@model IEnumerable<YugiOhCardViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Product List</h2>
        </div>
        <div class="col-8">
            <a asp-controller="YugiOhCard" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>  Search New Card
            </a>
        </div>
    </div>
</div>

<br/><br/>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
    <tr>
        <th>Card Nane</th>
        <th>Description</th>
        <th>Image</th>
        <th>Sets</th>
        <th>Price</th>
    </tr>
    </thead>
     <tbody>
        @foreach (var obj in Model)
        {
            <tr width="50%">
                <td>@obj.name</td>
                <td>@obj.descrtion</td>
                <td>
                    <img src="@obj.smallCardImages[0]" />
                </td>
                <td> @obj.sets[0] </td>
                <td> @obj.highestPrice </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="YugiOhCard" asp-action="DetailedCard" asp-route-cardName="@obj.name"><i class="btn btn-primary btn-sm">View</i></a>
                    </div>
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="YugiOhCard" asp-action="Delete" asp-route-cardName="@obj.name"><i class="btn btn-primary btn-sm">Delete</i></a>
                    </div>
                </td>
            </tr>
        }
        </tbody>
</table>

YugiOh_NonDBVersion/Views/YugiOhCard/Update.cshtml
@model YugiOhCardViewModel

<form method = "post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Product</h2>
            <hr/>
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="name"></label>
            <input asp-for="descrtion" class="form-control"/>
            @* <span asp-validation-for="Name" class="text-danger"></span> *@
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="YugiOhCard" asp-action="Update" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>